// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3Yaw7aMc6sxh7jBVnA-kGvkmuY6jVZc',
    appId: '1:721795337132:android:db3cfae0b515a3d6e40809',
    messagingSenderId: '721795337132',
    projectId: 'fir-basic-3901c',
    databaseURL: 'https://fir-basic-3901c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-basic-3901c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUt6NpXuhZ-Iv9fTazICkx4_d0End9nA',
    appId: '1:721795337132:ios:69311afc015b4602e40809',
    messagingSenderId: '721795337132',
    projectId: 'fir-basic-3901c',
    databaseURL: 'https://fir-basic-3901c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-basic-3901c.firebasestorage.app',
    androidClientId: '721795337132-0vq1soe12jjnuolk5ab4ak72re4g39o3.apps.googleusercontent.com',
    iosClientId: '721795337132-ua6ml3t7fvi0ig7t7bhml3il8enaoc1v.apps.googleusercontent.com',
    iosBundleId: 'com.diendanx.app.vivuvnApp',
  );
}
