version: "3.8"

services:
  vivuvn-ai-service:
    build:
      context: .
      dockerfile: Dockerfile
      # Optional: use cache from registry to speed up builds
      # cache_from:
      #   - vivuvn-ai-service:latest
    image: minhdang1163/vivuvn-ai-service:latest
    container_name: vivuvn-ai-service

    # Load environment variables from file
    # Create .env.docker from .env.docker template and update values
    env_file:
      - .env.docker

    # Port mapping (host:container)
    ports:
      - "8000:8000"

    restart: unless-stopped

    # Resource limits (optional but recommended for production)
    # Reduced memory requirements since using cloud-based embeddings
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G  # Reduced from 3G (no local ML models)
        reservations:
          cpus: "0.5"
          memory: 512M  # Reduced from 1G

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Network configuration
    networks:
      - vivuvn-network

# Networks
networks:
  vivuvn-network:
    driver: bridge
    name: vivuvn-network
