// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vivuvn_api.Data;

#nullable disable

namespace vivuvn_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelLocation", b =>
                {
                    b.Property<int>("NearbyHotelsId")
                        .HasColumnType("int");

                    b.Property<int>("NearbyLocationsId")
                        .HasColumnType("int");

                    b.HasKey("NearbyHotelsId", "NearbyLocationsId");

                    b.HasIndex("NearbyLocationsId");

                    b.ToTable("LocationHotel", (string)null);
                });

            modelBuilder.Entity("LocationRestaurant", b =>
                {
                    b.Property<int>("NearbyLocationsId")
                        .HasColumnType("int");

                    b.Property<int>("NearbyRestaurantsId")
                        .HasColumnType("int");

                    b.HasKey("NearbyLocationsId", "NearbyRestaurantsId");

                    b.HasIndex("NearbyRestaurantsId");

                    b.ToTable("LocationRestaurant", (string)null);
                });

            modelBuilder.Entity("vivuvn_api.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BudgetId");

                    b.HasIndex("ItineraryId")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("vivuvn_api.Models.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaidByMemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("BudgetTypeId");

                    b.HasIndex("PaidByMemberId");

                    b.ToTable("BudgetItems");
                });

            modelBuilder.Entity("vivuvn_api.Models.BudgetType", b =>
                {
                    b.Property<int>("BudgetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BudgetTypeId");

                    b.ToTable("BudgetTypes");
                });

            modelBuilder.Entity("vivuvn_api.Models.FavoritePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("LocationId");

                    b.ToTable("FavoritePlaces");
                });

            modelBuilder.Entity("vivuvn_api.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleMapsUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("UserRatingCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GooglePlaceId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("vivuvn_api.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysCount")
                        .HasColumnType("int");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<int>("DestinationProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupSize")
                        .HasColumnType("int");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("InviteCodeGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("TransportationVehicle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationProvinceId");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("[InviteCode] IS NOT NULL");

                    b.HasIndex("StartProvinceId");

                    b.HasIndex("UserId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("ItineraryId", "DayNumber");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetItemId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CheckOut")
                        .HasColumnType("date");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetItemId")
                        .IsUnique()
                        .HasFilter("[BudgetItemId] IS NOT NULL");

                    b.HasIndex("HotelId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ItineraryHotels");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryItem", b =>
                {
                    b.Property<int>("ItineraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryItemId"));

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<double?>("EstimateDuration")
                        .HasColumnType("float");

                    b.Property<int>("ItineraryDayId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<double?>("TransportationDistance")
                        .HasColumnType("float");

                    b.Property<double?>("TransportationDuration")
                        .HasColumnType("float");

                    b.Property<string>("TransportationVehicle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItineraryItemId");

                    b.HasIndex("ItineraryDayId");

                    b.HasIndex("LocationId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("UserId");

                    b.HasIndex("ItineraryId", "UserId")
                        .IsUnique();

                    b.ToTable("ItineraryMembers");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("ItineraryMemberId");

                    b.ToTable("ItineraryMessages");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetItemId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BudgetItemId")
                        .IsUnique()
                        .HasFilter("[BudgetItemId] IS NOT NULL");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ItineraryRestaurants");
                });

            modelBuilder.Entity("vivuvn_api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectionsUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlaceUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("ReviewUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GooglePlaceId");

                    b.HasIndex("NameNormalized");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("vivuvn_api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("vivuvn_api.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("vivuvn_api.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("vivuvn_api.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .IsUnique();

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("vivuvn_api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleMapsUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("UserRatingCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GooglePlaceId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("vivuvn_api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("vivuvn_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerificationTokenExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleIdToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RefreshTokenExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasFilter("[RefreshToken] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("vivuvn_api.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken")
                        .HasDatabaseName("IX_UserDevices_FcmToken");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserDevices_UserId_IsActive");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("vivuvn_api.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HotelLocation", b =>
                {
                    b.HasOne("vivuvn_api.Models.Hotel", null)
                        .WithMany()
                        .HasForeignKey("NearbyHotelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("NearbyLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocationRestaurant", b =>
                {
                    b.HasOne("vivuvn_api.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("NearbyLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("NearbyRestaurantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vivuvn_api.Models.Budget", b =>
                {
                    b.HasOne("vivuvn_api.Models.Itinerary", null)
                        .WithOne("Budget")
                        .HasForeignKey("vivuvn_api.Models.Budget", "ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vivuvn_api.Models.BudgetItem", b =>
                {
                    b.HasOne("vivuvn_api.Models.Budget", "Budget")
                        .WithMany("Items")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.BudgetType", "BudgetType")
                        .WithMany()
                        .HasForeignKey("BudgetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.ItineraryMember", "PaidByMember")
                        .WithMany()
                        .HasForeignKey("PaidByMemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Budget");

                    b.Navigation("BudgetType");

                    b.Navigation("PaidByMember");
                });

            modelBuilder.Entity("vivuvn_api.Models.FavoritePlace", b =>
                {
                    b.HasOne("vivuvn_api.Models.Itinerary", null)
                        .WithMany("FavoritePlaces")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("vivuvn_api.Models.Itinerary", b =>
                {
                    b.HasOne("vivuvn_api.Models.Province", "DestinationProvince")
                        .WithMany()
                        .HasForeignKey("DestinationProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.Province", "StartProvince")
                        .WithMany()
                        .HasForeignKey("StartProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.User", "User")
                        .WithMany("Itineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationProvince");

                    b.Navigation("StartProvince");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryDay", b =>
                {
                    b.HasOne("vivuvn_api.Models.Itinerary", null)
                        .WithMany("Days")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryHotel", b =>
                {
                    b.HasOne("vivuvn_api.Models.BudgetItem", "BudgetItem")
                        .WithOne("ItineraryHotel")
                        .HasForeignKey("vivuvn_api.Models.ItineraryHotel", "BudgetItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("vivuvn_api.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("vivuvn_api.Models.Itinerary", "Itinerary")
                        .WithMany("Hotels")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetItem");

                    b.Navigation("Hotel");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryItem", b =>
                {
                    b.HasOne("vivuvn_api.Models.ItineraryDay", "ItineraryDay")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("ItineraryDay");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryMember", b =>
                {
                    b.HasOne("vivuvn_api.Models.Itinerary", "Itinerary")
                        .WithMany("Members")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.User", "User")
                        .WithMany("ItineraryMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryMessage", b =>
                {
                    b.HasOne("vivuvn_api.Models.Itinerary", "Itinerary")
                        .WithMany("Messages")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.ItineraryMember", "ItineraryMember")
                        .WithMany()
                        .HasForeignKey("ItineraryMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("ItineraryMember");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryRestaurant", b =>
                {
                    b.HasOne("vivuvn_api.Models.BudgetItem", "BudgetItem")
                        .WithOne("ItineraryRestaurant")
                        .HasForeignKey("vivuvn_api.Models.ItineraryRestaurant", "BudgetItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("vivuvn_api.Models.Itinerary", "Itinerary")
                        .WithMany("Restaurants")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BudgetItem");

                    b.Navigation("Itinerary");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("vivuvn_api.Models.Location", b =>
                {
                    b.HasOne("vivuvn_api.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("vivuvn_api.Models.Notification", b =>
                {
                    b.HasOne("vivuvn_api.Models.Itinerary", "Itinerary")
                        .WithMany("Notifications")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("vivuvn_api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vivuvn_api.Models.PasswordReset", b =>
                {
                    b.HasOne("vivuvn_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("vivuvn_api.Models.Photo", b =>
                {
                    b.HasOne("vivuvn_api.Models.Hotel", "Hotel")
                        .WithMany("Photos")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("vivuvn_api.Models.Location", "Location")
                        .WithMany("Photos")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("vivuvn_api.Models.Restaurant", "Restaurant")
                        .WithMany("Photos")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Hotel");

                    b.Navigation("Location");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("vivuvn_api.Models.UserDevice", b =>
                {
                    b.HasOne("vivuvn_api.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("vivuvn_api.Models.UserRole", b =>
                {
                    b.HasOne("vivuvn_api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vivuvn_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vivuvn_api.Models.Budget", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("vivuvn_api.Models.BudgetItem", b =>
                {
                    b.Navigation("ItineraryHotel");

                    b.Navigation("ItineraryRestaurant");
                });

            modelBuilder.Entity("vivuvn_api.Models.Hotel", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("vivuvn_api.Models.Itinerary", b =>
                {
                    b.Navigation("Budget");

                    b.Navigation("Days");

                    b.Navigation("FavoritePlaces");

                    b.Navigation("Hotels");

                    b.Navigation("Members");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("vivuvn_api.Models.ItineraryDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("vivuvn_api.Models.Location", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("vivuvn_api.Models.Restaurant", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("vivuvn_api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("vivuvn_api.Models.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Itineraries");

                    b.Navigation("ItineraryMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
